name: aroggyapath
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^3.1.0
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # HTTP & API
  http: ^1.1.0
  
  # Localization
  flutter_localizations:
    sdk: flutter

  # WebRTC & Socket
  permission_handler: ^12.0.1
  wakelock_plus: ^1.2.8
  url_launcher: ^6.2.0
 
  # Media Handling
  image_picker: ^1.2.1
  video_player: ^2.8.1
  video_thumbnail: ^0.5.3
  
  # OpenStreetMap (flutter_map)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Utilities
  intl: ^0.20.2
  share_plus: ^7.2.1
  json_annotation: ^4.8.1
  
  # Firebase
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  
  # Local Notifications & Video Calls
  flutter_local_notifications: ^19.5.0
  jitsi_meet_flutter_sdk: ^0.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_gen: ^5.12.0
  flutter_image_compress: ^2.4.0
  photo_view: ^0.15.0
  gal: ^2.3.2
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.2
  supabase_flutter: ^2.8.1

  #snackbar
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  image: ^4.0.17 
  flutter_native_splash: ^2.4.0 
  flutter_launcher_icons: ^0.13.1 

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/

        # - assets/images/icon.png
    # - assets/images/onboarding1.png
    # - assets/images/onboarding2.png
    # - assets/images/onboarding3.png
    # - assets/images/patient.png
    # - assets/images/doctor.png
    # - assets/images/doctors.png
    # - assets/images/map.png
    # - assets/images/profile.png
    # - assets/images/doctor_booking.png
    # - assets/images/doctor1.png
    # - assets/images/doctor2.png
    # - assets/images/doctor3.png
    # - assets/images/doctor4.png
    # - assets/images/doctor5.png
    # - assets/images/reelsviewdoctor.png
    # - assets/images/news.png
    # - assets/images/algerian.png

  